import { createElement } from 'lwc';
import A6MotorHakkinda from 'c/a6MotorHakkinda';

describe('c-a6-motor-hakkinda', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-a6-motor-hakkinda', {
            is: A6MotorHakkinda
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});