import { createElement } from 'lwc';
import A1DataBindingManipule from 'c/a1DataBindingManipule';

describe('c-a1-data-binding-manipule', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-a1-data-binding-manipule', {
            is: A1DataBindingManipule
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});